/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as AgentHistoryRouteImport } from './routes/agent.history'
import { Route as AgentRunIdRouteImport } from './routes/agent.run.$id'

const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRoute,
} as any)
const AgentHistoryRoute = AgentHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AgentRoute,
} as any)
const AgentRunIdRoute = AgentRunIdRouteImport.update({
  id: '/run/$id',
  path: '/run/$id',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/agent/history': typeof AgentHistoryRoute
  '/agent/': typeof AgentIndexRoute
  '/agent/run/$id': typeof AgentRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent/history': typeof AgentHistoryRoute
  '/agent': typeof AgentIndexRoute
  '/agent/run/$id': typeof AgentRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/agent/history': typeof AgentHistoryRoute
  '/agent/': typeof AgentIndexRoute
  '/agent/run/$id': typeof AgentRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent' | '/agent/history' | '/agent/' | '/agent/run/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent/history' | '/agent' | '/agent/run/$id'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/agent/history'
    | '/agent/'
    | '/agent/run/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/history': {
      id: '/agent/history'
      path: '/history'
      fullPath: '/agent/history'
      preLoaderRoute: typeof AgentHistoryRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/run/$id': {
      id: '/agent/run/$id'
      path: '/run/$id'
      fullPath: '/agent/run/$id'
      preLoaderRoute: typeof AgentRunIdRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface AgentRouteChildren {
  AgentHistoryRoute: typeof AgentHistoryRoute
  AgentIndexRoute: typeof AgentIndexRoute
  AgentRunIdRoute: typeof AgentRunIdRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentHistoryRoute: AgentHistoryRoute,
  AgentIndexRoute: AgentIndexRoute,
  AgentRunIdRoute: AgentRunIdRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
